window.APP_CONFIG = {
  SUPABASE_URL: "https://YOUR_PROJECT_ID.supabase.co",
  SUPABASE_ANON_KEY: "YOUR_SUPABASE_ANON_KEY",
  CLASS_ID: "4C",
  TEACHER_PASSWORD_HASH: "SHA256_HEX_OF_TEACHER_PASSWORD"
};
